version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      # Ignores any major updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      # Ignores any major and minor updates, because @angular-devkit/architect@0.x.x has a non-standard angular semantic
      # version number
      - dependency-name: '@angular-devkit/architect'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      # Ignores any major and minor updates, because @angular-devkit/architect-cli@0.x.x has a non-standard angular
      # semantic version number
      - dependency-name: '@angular-devkit/architect-cli'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@types/eslint'
          - '@typescript-eslint/*'
          - '@angular-eslint/*'
          - '@stylistic/*'
      prettier:
        patterns:
          - 'prettier*'
      stylelint:
        patterns:
          - 'stylelint*'
      commitlint:
        patterns:
          - '@commitlint/*'
      cspell:
        patterns:
          - 'cspell'
          - '@cspell/*'
      angular:
        patterns:
          - '@angular/*'
          - 'rxjs'
          - 'zone.js'
          - '@angular-builders/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'ng-packagr'
          - 'tslib'
      ag-grid:
        patterns:
          - '@koobiq/ag-grid-angular-theme'
          - 'ag-grid-*'
      koobiq:
        patterns:
          - '@koobiq/*'
      docsearch:
        patterns:
          - '@docsearch/*'
      rollup:
        patterns:
          - 'rollup*'
          - '@rollup/*'
      conventional-changelog:
        patterns:
          - 'conventional-changelog*'
          - '@conventional-changelog/*'
          - '@types/conventional-changelog'
          - '@types/conventional-changelog-writer'
      jest:
        patterns:
          - 'jest*'
          - '@types/jest'
          - 'ts-jest'
      karma:
        patterns:
          - 'karma*'
          - 'jasmine*'
          - 'karma-jasmine*'
          - '@types/jasmine'
          - '@types/karma'
          - '@types/karma-jasmine'
          - '@types/karma-spec-reporter'
      nunjucks:
        patterns:
          - 'nunjucks'
          - '@types/nunjucks'
      spdx-satisfies:
        patterns:
          - 'spdx-satisfies'
          - '@types/spdx-satisfies'
      merge2:
        patterns:
          - 'merge2'
          - '@types/merge2'
      inquirer:
        patterns:
          - 'inquirer'
          - '@types/inquirer'
      chalk:
        patterns:
          - 'chalk'
          - '@types/chalk'
      fs-extra:
        patterns:
          - 'fs-extra'
          - '@types/fs-extra'
      glob:
        patterns:
          - 'glob'
          - '@types/glob'
      luxon:
        patterns:
          - 'luxon'
          - '@types/luxon'
      express:
        patterns:
          - 'express'
          - '@types/express'
