name: Deploy to Hosting on PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  checks: write
  contents: read
  pull-requests: write # for FirebaseExtended/action-hosting-deploy to comment on PRs

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/setup-yarn

      - uses: ./.github/workflows/actions/build-packages

      - uses: ./.github/workflows/actions/build-docs

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOOBIQ }}'
          expires: 5d
          channelId: prs-${{ github.event.number }}
          projectId: koobiq
          target: next
