name: Deploy to Hosting on PR

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write # for FirebaseExtended/action-hosting-deploy to comment on PRs

jobs:
  deploy_live:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/workflows/actions/setup-node

      - name: Build Packages
        uses: ./.github/workflows/actions/build-packages

      - name: Build Documentation
        uses: ./.github/workflows/actions/build-docs

      - name: Deploy Documentation
        if: github.actor != 'dependabot[bot]'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOOBIQ }}'
          firebaseToolsVersion: '13.35.1'
          expires: 5d
          channelId: prs-${{ github.event.number }}
          projectId: koobiq
          target: next
