name: Deploy to Hosting on PR

on:
  pull_request_target:
    branches:
      - main
#    types:
#      - opened
#      - reopened
#      - synchronize
#      - labeled

permissions:
  checks: write
  contents: read
  pull-requests: write # for FirebaseExtended/action-hosting-deploy to comment on PRs

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Yarn
        uses: ./.github/workflows/actions/setup-yarn

      - uses: ./.github/workflows/actions/build-packages

      - uses: ./.github/workflows/actions/build-docs

      - name: Deploy Documentation
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOOBIQ }}'
          expires: 5d
          channelId: prs-${{ github.event.number }}
          projectId: koobiq
          target: next
