name: Publish

on:
  push:
    tags:
      - '*.*.*'
      # - '[0-9]+.[0-9]+.[0-9]+'
      # - '*@*.*.*' for NX integration

permissions:
  contents: read
  packages: write
  id-token: write # needed for provenance data generation

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'koobiq' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        uses: ./.github/actions/setup-yarn

      - name: Build
        run: |
          yarn run build:cdk
          yarn run build:components
          yarn run build:angular-luxon-adapter
          yarn run build:angular-moment-adapter
          yarn run styles:built-all
          yarn run build:cli

      - name: Publish package
        run: |
          rm -rf .npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_KOOBIQ" > ~/.npmrc
          npm run release:publish:ci-github
        env:
          NPM_TOKEN_KOOBIQ: ${{ secrets.NPM_PUBLISH_TOKEN }}
