name: Publish

on:
  push:
    tags:
      - '*.*.*'
      # - '[0-9]+.[0-9]+.[0-9]+'
      # - '*@*.*.*' for NX integration

permissions:
  contents: read
  packages: write
  id-token: write # needed for provenance data generation

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'koobiq' }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: ./.github/workflows/actions/setup-node

      - name: Build packages
        uses: ./.github/workflows/actions/build-packages

      - name: Publish package
        run: |
          rm -rf .npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_KOOBIQ" > ~/.npmrc
          npm run release:publish:ci-github -- -t latest
        env:
          NPM_TOKEN_KOOBIQ: ${{ secrets.NPM_PUBLISH_TOKEN }}
          MATTERMOST_ENDPOINT_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: ${{ secrets.MM_CHANNEL_NAME }}
