name: Publish

on:
  push:
    tags:
      - '*.*.*'
      # - '[0-9]+.[0-9]+.[0-9]+'
      # - '*@*.*.*' for NX integration

permissions:
  contents: read
  packages: write
  id-token: write # needed for provenance data generation

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'koobiq' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        uses: ./.github/workflows/actions/setup-yarn

      - name: Build packages
        uses: ./.github/workflows/actions/build-packages

      - name: Publish package
        run: |
          rm -rf .npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_KOOBIQ" > ~/.npmrc
          npm run release:publish:ci-github
        env:
          NPM_TOKEN_KOOBIQ: ${{ secrets.NPM_PUBLISH_TOKEN }}

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
      - name: Extract current changelog
        id: extract-changelog
        run: |
          yarn run release:extract-changelog
          echo "CHANGELOG=$(cat ./CHANGELOG_CURRENT.md)" >> $GITHUB_OUTPUT

      - name: Notification
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          PAYLOAD: |-
            {
              "text": "${{ steps.extract-changelog.outputs.CHANGELOG }}",
              "channel": "${{ secrets.MM_CHANNGEL_NAME }}",
              "name": "${{ secrets.MM_BOT_NAME }}"
            }
